[program:vscode]
command=/usr/local/bin/code-server --port=8054 --auth none --disable-update-check --disable-telemetry --user-data-dir=%(ENV_WORKSPACE_RUNTIME_HOME)s/.config/Code/ --extensions-dir=%(ENV_WORKSPACE_RUNTIME_HOME)s/.vscode/extensions/ --auth=none %(ENV_WORKSPACE_HOME)s/
user=%(ENV_WORKSPACE_RUNTIME_USER)s
environment=HOME="%(ENV_WORKSPACE_RUNTIME_HOME)s",USER="%(ENV_WORKSPACE_RUNTIME_USER)s"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log ; log logs into file
startretries=5   ; max # of serial start failures (default 3)
